version: '3'
services:
  db:
    container_name: webmysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_ROOT_PASSWORD: "rootpass"
      MYSQL_DATABASE: "testdb"
  web:
    container_name: webapp
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    dns: 8.8.8.8
    command: bash -c "chmod -R 777 /var/www/html && 
      cd /var/www/html && 
      cp .env.example .env && 
      composer install && 
      php artisan key:generate && 
      php artisan migrate && 
      service apache2 restart && 
      tail -f /dev/null"
    links:
      - db
    depends_on:
      - db
